api:

  common:
    version: 1.0.0
    title: products API
    description: API of products
    termsOfServiceUrl: www.term-service.com
    license: License
    licenseUrl: www.myurl-license.com

    contact:
      name: Lockin
      url: https://www.linkedin.com/in/javier-almario
      email: javieralmario12@gmail.com

  product-composite:

    get-composite-product:
      description: Returns a composite view of the specified product id
      notes: |
        If the requested product id is found the method will return information regarding:
        1. Base product information
        1. Reviews
        1. Recommendations
        1. Service Addresses\n(technical information regarding the addresses of the microservices that created the response)

        In the following cases, only a partial response be created (used to simplify testing of error conditions)

        200 - Ok, but no recommendations will be returned

        200 - Ok, but no reviews will be returned

        400 - A <b>Bad Request</b> error will be returned

        404 - A <b>Not Found</b> error will be returned

        422 - An <b>Unprocessable Entity</b> error will be returned



server:
    port: 7000
app:
    product-service:
        host: localhost
        port: 7001
    recommendation-service:
        host: localhost
        port: 7002
    review-service:
        host: localhost 
        port: 7003

---
spring.profiles: docker

server.port: 8080

app:
  product-service:
    host: product
    port: 8080
  recommendation-service:
    host: recommendation
    port: 8080
  review-service:
    host: review
    port: 8080
